### ISSUE TITLE
Reward based on state changes

### ISSUE THREAD

**Issue by hifzajaved** [AdaCompNUS/despot#11]
Hi, I just had a quick question about possibly designing the reward matrix for a POMDP using the difference in the previous and current states, rather than the action. I see in the examples you have provided, all the reward matrices are dependent only on the previous state and action. Is there a reward function in DESPOT that accepts a different set of arguments?

**Comment by davidyhsu** [comment]
> Hi, I just had a quick question about possibly designing the reward matrix for a POMDP using the difference in the previous and current states, rather than the action. I see in the examples you have provided, all the reward matrices are dependent only on the previous state and action.
> 

R(s,a, s’) based on the standard definition of the POMDP formalism.

—David
