### ISSUE TITLE
<InitialStateBelief>: 1 entries expected but 4 found.

### ISSUE THREAD

**Issue by neuronphysics** [AdaCompNUS/despot#15]
Hi I specified in my POMDP model a latent state of time which has 4 states and it is kind of important to define it for the rest of my problem. I defined time states in the xml file first as follows 
```
<StateVar vnamePrev="time_0" vnameCurr="time_1" fullyObs="false">
<ValueEnum>4</ValueEnum>
</StateVar>
```
Then I initialized its state values as
```
</CondProb>
<CondProb>
<Var>time_0</Var>
<Parent>null</Parent>
<Parameter type = "TBL">
<Entry>
<Instance>-</Instance>
<ProbTable>1.0 0.0 0.0 0.0</ProbTable>
</Entry>
</Parameter>
</CondProb>
```
But I get the following error for giving a vector of probabilities for state of time starting off with deterministic value of 1 for the first state and the rest will be zero:
```
ERROR: ./data/StarMaze.pomdpx:58:
 In <InitialStateBelief>: 1 entries expected but 4 found.

```
The errors are vague and the document doesn't clear up details and it is hard to figure out what causes this error. I appreciate if you can suggest why I get this error. Thanks

**Comment by cindycia** [comment]
Hi there, the POMDPX mode of DESPOT is deprecated. You may have a try on the C++ version.
