### ISSUE TITLE
How to specify a different sampling technique

### ISSUE THREAD

**Issue by alphonsusadubredu** [AdaCompNUS/despot#16]
I'm applying DESPOT for a robot grocery packing task. The robot's observation is represented by a vector of probabilities for  each of the grocery items observed. Because of this, I find it difficult to represent the problem in a suitable manner on which I can apply DESPOT. My main issue currently is about how to modify the DESPOT sampler to sample from the vector of probabilities for each of the observed grocery items. Do you have any idea about how to go about this?

**Comment by zsunberg** [comment]
Hi @alphonsusadubredu just saw this in my email notifications for repositories I follow. Wanted to let you know that we have a [POMDPs.jl](https://github.com/JuliaPOMDP/POMDPs.jl) implementation of [DESPOT](https://github.com/JuliaPOMDP/ARDESPOT.jl) that might be able to accommodate your problem. In particular, a vector of grocery items with probabilities can be represented like this:
```julia
SparseCat(["milk", "bread", "eggs"], [0.1, 0.7, 0.2])
```
(SparseCat is short for "sparse categorical distribution"). Feel free to reach out on our [Discussions page](https://github.com/JuliaPOMDP/POMDPs.jl/discussions) if you're interested in talking about this more.

**Comment by alphonsusadubredu** [comment]
Thank you

**Comment by cindycia** [comment]
> I'm applying DESPOT for a robot grocery packing task. The robot's observation is represented by a vector of probabilities for each of the grocery items observed. Because of this, I find it difficult to represent the problem in a suitable manner on which I can apply DESPOT. My main issue currently is about how to modify the DESPOT sampler to sample from the vector of probabilities for each of the observed grocery items. Do you have any idea about how to go about this?

I assume that you mean your observation probability is represented explicitly and you want to sample observations from the distribution. 

In this case, you can implement your observation sampler in the step function (in a DSPOMDP child class). DESPOT treats the step function as a black box and only expects it to output a sampled observation.

**Comment by alphonsusadubredu** [comment]
Alright. I'll do that. Thank you for your help!
