### ISSUE TITLE
DESPOT has incorrect termination condition

### ISSUE THREAD

**Issue by mkoval** [AdaCompNUS/despot#6]
DESPOT accepts both a maximum number of scenarios to run and a timeout. I expected the planner to terminate when either condition was violated. However, that is [not currently the case](https://github.com/AdaCompNUS/despot/blob/master/src/solver/despot.cpp#L147):

```c++
do {
  double start = clock();
  VNode* cur = Trial(root, streams, lower_bound, upper_bound, model, history, statistics);
  used_time += double(clock() - start) / CLOCKS_PER_SEC;

  start = clock();
  Backup(cur);
  if (statistics != NULL) {
    statistics->time_backup += double(clock() - start) / CLOCKS_PER_SEC;
  }
  used_time += double(clock() - start) / CLOCKS_PER_SEC;

  num_trials++;
} while (used_time * (num_trials + 1.0) / num_trials < timeout
  && (root->upper_bound() - root->lower_bound()) > 1e-6);
```

Building the DESPOT only terminates when (1) the gap between the upper and lower bounds at the root node is nearly zero or (2) the timeout expires. If the K scenarios are exhausted before then the loop continues to iterate, seemingly doing nothing because the `RandomStreams` are depleted, until the timeout expires.

**Comment by yenan** [comment]
hi Michael,

i'm not sure i understand your question.

> DESPOT accepts both a maximum number of scenarios to run and a timeout. I
> expected the planner to terminate when either condition was violated.
> However, that is not currently the case
> <https://github.com/AdaCompNUS/despot/blob/master/src/solver/despot.cpp#L147>
> :
>
the number of scenarios is fixed. which maximum are you referring to?


> do {
>   double start = clock();
>   VNode* cur = Trial(root, streams, lower_bound, upper_bound, model, history, statistics);
>   used_time += double(clock() - start) / CLOCKS_PER_SEC;
>
>   start = clock();
>   Backup(cur);
>   if (statistics != NULL) {
>     statistics->time_backup += double(clock() - start) / CLOCKS_PER_SEC;
>   }
>   used_time += double(clock() - start) / CLOCKS_PER_SEC;
>
>   num_trials++;
> } while (used_time * (num_trials + 1.0) / num_trials < timeout
>   && (root->upper_bound() - root->lower_bound()) > 1e-6);
>
> Building the DESPOT only terminates when (1) the gap between the upper and
> lower bounds at the root node is nearly zero or (2) the timeout expires. If
> the K scenarios are exhausted before then the loop continues to iterate,
> seemingly doing nothing because the RandomStreams are depleted, until the
> timeout expires.
>
> by exhausted, did you mean the whole DESPOT has been explored but the
search still continues? this shouldn't be the case. but if it indeed
happens, please send me the details.

- Nan

**Comment by mkoval** [comment]
You're absolutely correct - I had a fundamental misunderstanding of what this loop was going (see my reply via email). I am closing this issue.
